# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='state',
            field=models.CharField(choices=[('read', 'Read'), ('wish', 'Wish'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
