# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0002_auto_20170426_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='image', max_length=500),
        ),
    ]
