# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0007_auto_20170428_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
