# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0008_auto_20170428_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='bs_app/static/bs_app/images'),
        ),
    ]
