# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0012_auto_20170428_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_notification_id',
            field=models.IntegerField(default=1),
        ),
    ]
