# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0013_profile_last_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bs_app.Book'),
        ),
    ]
