# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0014_notification_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.Book'),
        ),
    ]
