# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0016_auto_20170430_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.FileField(null=True, upload_to='bs_app/static/bs_app/images/authors'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(null=True, upload_to='bs_app/static/bs_app/images/categories'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(null=True, upload_to='bs_app/static/bs_app/images/books'),
        ),
    ]
