# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0018_auto_20170430_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
