# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0020_author_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
